version: "3"

services:
  app:
    build: .
    ports:
      - 4000:4000
    command: mix phx.server
    volumes:
      - .:/app/
      - node_modules:/app/assets/node_modules
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5433:5432
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  node_modules:
  postgres:
